export const SET_ROW = "SET_ROW";
export const SET_COLUMN = "SET_COLUMN";

export const TOGGLE_DRAW_MODE = "TOGGLE_DRAW_MODE";
export const TOGGLE_ERASE_MODE = "TOGGLE_ERASE_MODE";
export const CHANGE_SHAPE = "CHANGE_SHAPE";
export const CHANGE_SIZE = "CHANGE_SIZE";

export const TOGGLE_PLAY = "TOGGLE_PLAY";
export const CHANGE_SPEED = "CHANGE_SPEED";

export const SET_START_COLOR = "SET_START_COLOR";
export const SET_END_COLOR = "SET_END_COLOR";
export const TOGGLE_INFINITE_LIFE = "TOGGLE_INFINITE_LIFE";
export const CHANGE_LIFESPAN = "CHANGE_LIFESPAN";
